### ISSUE TITLE
Consdier using something other than bzip to archive data

### ISSUE THREAD

**Issue by valarauca** [Runemoro/better-renderer#15]
I'm curious by bzip2 was chosen as it is a rather poor compression algorithm, [cite](https://quixdb.github.io/squash-benchmark/).

Would you be willing to consider switching? I would happily do some of the leg work on this. I was eying `zstd`, but it would require using the JNI, is that prohibited in runelite?

**Comment by Runemoro** [comment]
Because the Jagex server sends bzip compressed files. On the disk, they are stored uncompressed.
