### ISSUE TITLE
Lighting looks worse than base game / is non existent.

### ISSUE THREAD

**Issue by zeakzz** [Runemoro/better-renderer#4]
Are there any plans to try to get the game too look less bright?
![1](https://user-images.githubusercontent.com/63619162/98640673-4aa04180-22df-11eb-86e1-a60e7b172525.PNG)
![2](https://user-images.githubusercontent.com/63619162/98640686-50962280-22df-11eb-8107-2c50f95f15c9.PNG)
Personally the game looks way to bright, im loving everything else though. I hope this is something that can be changed / fixed in the future.

**Comment by Runemoro** [comment]
The plugin is still in early beta, and many things will be improved, lighting and textures being one those.

**Comment by Runemoro** [comment]
Brightness should be fixed in the [next release](https://github.com/runelite/plugin-hub/pull/783).
